services:
  backend:
#    image: ghcr.io/loudbooks/pastebook-backend:latest
    build:
      context: ./backend
    restart: always
    security_opt:
      - "no-new-privileges:true"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/pastebook
      - SPRING_DATA_MONGODB_DATABASE=pastebook
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=pastebook
      - S3_ENDPOINT=http://minio:9000
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - pastebook-network

  frontend:
    image: ghcr.io/loudbooks/pastebook-frontend:latest
#    build:
#      context: ./frontend
    restart: always
    security_opt:
      - "no-new-privileges:true"
    environment:
      - TITLE=${TITLE}
      - DESCRIPTION=${DESCRIPTION}
      - DISABLE_NEW=${DISABLE_NEW}
      - FAVICON_URL=${FAVICON_URL}
      - MAX_PAYLOAD_SIZE=${MAX_PAYLOAD_SIZE}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - pastebook-network
    pull_policy: always

  nginx:
    image: nginx:latest
    depends_on:
      - backend
      - frontend
    security_opt:
      - "no-new-privileges:true"
    expose:
      - "80"
    #environment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailman.entrypoints=websecure"
      - "traefik.http.routers.mailman.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.mailman.tls.certresolver=http-challenge"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pastebook-network
      - nginx-proxy

  mongo:
    image: mongo:6.0
    restart: always
    security_opt:
      - "no-new-privileges:true"
    environment:
      MONGO_INITDB_DATABASE: pastebook
    volumes:
      - mongo-data:/data/db
    networks:
      - pastebook-network
    pull_policy: always

  minio:
    image: quay.io/minio/minio:latest
    restart: always
    security_opt:
      - "no-new-privileges:true"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data/db
    networks:
      pastebook-network:
        aliases:
            - pastebook.minio
    pull_policy: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 2s
      retries: 5
    command: server /data/db

volumes:
  mongo-data:
  minio-data:

networks:
  pastebook-network:
  traefik-proxy:
    external: true
