services:
  backend:
#    image: ghcr.io/loudbooks/pastebook-backend:latest
#    container_name: pastebook-backend
    build:
      context: ./backend
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap-drop:
      - SETUID
      - SETGID
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/pastebook
      - SPRING_DATA_MONGODB_DATABASE=pastebook
      - S3_ACCESS_KEY_ID=minioadmin
      - S3_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=pastebook
      - S3_ENDPOINT=http://minio:9000
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - pastebook-network

  frontend:
    image: ghcr.io/loudbooks/pastebook-frontend:latest
#    container_name: pastebook-frontend
#    build:
#      context: ./frontend
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap-drop:
      - SETUID
      - SETGID
    environment:
      - TITLE=${TITLE}
      - DESCRIPTION=${DESCRIPTION}
      - DISABLE_NEW=${DISABLE_NEW}
      - FAVICON_URL=${FAVICON_URL}
      - MAX_PAYLOAD_SIZE=${MAX_PAYLOAD_SIZE}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - backend
    networks:
      - pastebook-network
    pull_policy: always

  nginx:
    image: nginx:latest
    depends_on:
      - backend
      - frontend
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap-drop:
      - SETUID
      - SETGID
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:?missing VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:?missing LETSENCRYPT_EMAIL}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    networks:
      - pastebook-network
      - nginx-proxy

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap-drop:
      - SETUID
      - SETGID
    environment:
      MONGO_INITDB_DATABASE: pastebook
    volumes:
      - mongo-data:/data/db
    networks:
      - pastebook-network
    pull_policy: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    command: server /data/db
    user: ${PUID:-1000}:${PGID:-1000}
    security_opt:
      - "no-new-privileges:true"
    cap-drop:
      - SETUID
      - SETGID
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data/db
    networks:
      pastebook-network:
        aliases:
            - pastebook.minio
    pull_policy: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  mongo-data:
  minio-data:

networks:
  pastebook-network:
  nginx-proxy:
    external: true
  nginx-proxy:
    external: true
